Update 20241204

diff --git a/bin/dir2sb b/bin/dir2sb
--- a/bin/dir2sb
+++ b/bin/dir2sb
@@ -2,108 +2,116 @@
 # Author: Tomas M. <http://www.slax.org/>
 # Author: crims0n <https://minios.dev>
 
-read_config() {
-    # Enable extended globbing. This is required for the pattern matching of variable names.
-    shopt -s extglob
+VERSION="1.2"
+BEXT="sb"
+COMP_TYPE="zstd"
+export TEXTDOMAIN="minios-tools"
 
-    # The first argument is the configuration file.
-    local CONFIG_FILE="${1?No configuration file given}"
+help() {
+    echo "$(gettext "Usage"): $(basename $0) [OPTIONS]... SOURCE_DIRECTORY [TARGET_FILE]"
+    echo "$(gettext "Converts a directory to a compressed .sb module")"
+    echo ""
+    echo "$(gettext "Options"):"
+    echo "  -b, --bext EXT              $(gettext "Bundle extension. Default: sb")"
+    echo "  -c, --comp TYPE             $(gettext "Compression type (zstd, gzip, lzo, xz). Default: zstd")"
+    echo "      --help                  $(gettext "Display this help and exit")"
+    echo "      --version               $(gettext "Display version information and exit")"
+    echo ""
+    echo "$(gettext "Arguments"):"
+    echo "  SOURCE_DIRECTORY            $(gettext "The directory to convert to a module")"
+    echo "  TARGET_FILE                 $(gettext "Optional. The name of the output module file")"
+    echo ""
+    echo "$(gettext "Behavior"):"
+    echo "  * $(gettext "If SOURCE_DIRECTORY does not have a .sb extension and is not 'squashfs-root', then the directory itself is included in the module, and TARGET_FILE is required.")"
+    echo "  * $(gettext "If TARGET_FILE is not specified, SOURCE_DIRECTORY is replaced by the new module file.")"
+    exit 0
+}
 
-    # All other arguments are the variable names to look for.
-    local KEYLIST="${@:2}"
+brief_help() {
+    echo "$(gettext "Usage"): $(basename $0) [OPTIONS]... SOURCE_DIRECTORY [TARGET_FILE]"
+    echo "$(gettext "Try") '$(basename $0) --help' $(gettext "for more information.")"
+    exit 1
+}
 
-    # Check if the configuration file exists and is readable.
-    if [[ ! -f "${CONFIG_FILE}" ]]; then
-        echo >&2 "\"${CONFIG_FILE}\" is not a file!"
-        exit 1
-    fi
-    if [[ ! -r "${CONFIG_FILE}" ]]; then
-        echo >&2 "\"${CONFIG_FILE}\" is not readable!"
-        exit 1
-    fi
+version() {
+    echo "$(basename $0) $VERSION"
+    exit 0
+}
 
-    # Convert the list of variable names to a regex pattern.
-    KEYLIST="${KEYLIST// /|}"
-
-    # Read each line of the file.
-    while IFS='= ' read -r LHS RHS; do
-        # If the variable name is in our list and the value is not empty...
-        if [[ "${LHS}" =~ ^(${KEYLIST})$ ]] && [[ -n ${RHS} ]]; then
-            # Remove any quotes around the value.
-            RHS="${RHS%\"*}"
-            RHS="${RHS#\"*}"
-            RHS="${RHS%\'*}"
-            RHS="${RHS#\'*}"
-
-            # If the value is an array (surrounded by parentheses)...
-            if [[ "${RHS}" =~ ^\((.*)\)$ ]]; then
-                # Assign the array to the variable.
-                eval ${LHS}=\("${BASH_REMATCH[1]}"\)
-            else
-                # Otherwise, assign the value to the variable.
-                eval ${LHS}=\"${RHS}\"
-            fi
+while [ $# -gt 0 ]; do
+    case "$1" in
+    -b | --bext)
+        BEXT="$2"
+        shift 2
+        ;;
+    -c | --comp)
+        COMP_TYPE="$2"
+        shift 2
+        ;;
+    --help)
+        help
+        ;;
+    --version)
+        version
+        ;;
+    *)
+        if [ "$1" == -* ]; then # unknown option
+            brief_help
         fi
-    done <<<"$(tr -d '\r' <${CONFIG_FILE})"
+        POSARGS+=("$1")
+        shift
+        ;;
+    esac
+done
 
-    # Disable extended globbing after we're done using it.
-    shopt -u extglob
-}
-
-read_config /etc/minios/config BEXT COMP_TYPE
-
-usage() {
-   echo ""
-   echo "Convert directory to .sb compressed module"
-   echo "Usage: $0 [source_directory.sb] [[target_file.sb]]"
-   echo "  If source_directory does not have .sb suffix and it is not 'squashfs-root',"
-   echo "  then the source_directory itself is included in the module and"
-   echo "  then the target_file.sb parameter is required."
-   echo "  If target_file.sb is not specified, the source_directory is erased"
-   echo "  and replaced by the newly generated module file."
-}
-
-P1="$(readlink -f "$1")"
-P2="$(readlink -f "$2")"
-
-if [ "$P1" = "$P2" ]; then
-   P2=""
+if [ ${#POSARGS[@]} -eq 0 ]; then
+    brief_help
+elif [ ${#POSARGS[@]} -gt 2 ]; then
+    brief_help
 fi
 
-SB=$(echo "$P1" | grep -o "[.]sb/*\$")
+P1="$(readlink -f "${POSARGS[0]}")"
+P2=""
+if [ ${#POSARGS[@]} -eq 2 ]; then
+    P2="$(readlink -f "${POSARGS[1]}")"
+fi
+
+if [ "$P1" = "$P2" ]; then
+    P2=""
+fi
+
+SB=$(echo "$P1" | grep -o "[.]${BEXT}/*\$")
 if [ "$(echo "$P1" | grep -o "/squashfs-root/*\$")" != "" ]; then
-   SB="true"
+    SB="true"
 fi
 
 if [ "$SB" = "" ]; then
-   KEEP="-keep-as-directory"
-   if [ "$P2" = "" ]; then
-      usage
-      exit 1
-   fi
+    KEEP="-keep-as-directory"
+    if [ "$P2" = "" ]; then
+        brief_help
+    fi
 else
-   KEEP=""
+    KEEP=""
 fi
 
 if [ ! -d "$P1" ]; then
-   echo "Not a directory: $P1" >&2
-   exit 2
+    echo "$(gettext "Error"): $(gettext "Not a directory:") $P1" >&2
+    exit 2
 fi
 
 if [ "$P2" = "" ]; then
-   TARGET="$P1".$BEXT
-   while [ -e "$TARGET" ]; do TARGET="$TARGET"x; done
-   mksquashfs "$P1" "$TARGET" -comp $COMP_TYPE -b 1024K -always-use-fragments $KEEP >/dev/null || exit 3
+    TARGET="$P1.$BEXT"
+    while [ -e "$TARGET" ]; do TARGET="$TARGET"x; done
+    mksquashfs "$P1" "$TARGET" -comp "$COMP_TYPE" -b 1024K -always-use-fragments "$KEEP" ${COMP_TYPE:="zstd":+ "-Xcompression-level 19"} ${COMP_TYPE:="xz":+ "-Xbcj x86"} || echo "$(gettext "Error"): $(gettext "mksquashfs failed.")" >&2 && exit 3
 
-   umount "$P1" 2>/dev/null
-   rm -Rf "$P1"
-   mv "$TARGET" "$P1"
+    umount "$P1" 2>/dev/null
+    rm -Rf "$P1"
+    mv "$TARGET" "$P1"
 else
-   if [ -e "$P2" ]; then
-      echo "Target exists: $P2" >&2
-      exit 4
-   fi
+    if [ -e "$P2" ]; then
+        echo "$(gettext "Error"): $(gettext "Target exists:") $P2" >&2
+        exit 4
+    fi
 
-   mksquashfs "$P1" "$P2" -comp $COMP_TYPE -b 1024K -always-use-fragments $KEEP >/dev/null
-
+    mksquashfs "$P1" "$P2" -comp "$COMP_TYPE" -b 1024K -always-use-fragments "$KEEP" ${COMP_TYPE:="zstd":+ "-Xcompression-level 19"} ${COMP_TYPE:="xz":+ "-Xbcj x86"} || echo "$(gettext "Error"): $(gettext "mksquashfs failed.")" >&2
 fi
